# Generated by Django 3.2.2 on 2021-05-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_tag_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='courses',
            field=models.ManyToManyField(related_name='contents', to='api.Course'),
        ),
    ]
